name: Deploy
description: Deploy using serverless framework
inputs:
  path:  
    description: Path to Service
    required: true
  stage: 
    description: Stage
    required: true
    default: DEVELOPMENT
 
runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3

    - name: Install Serverless Framework CLI
      shell: bash
      run: |
        npm install -g serverless@3.x

    - name: Deploy
      shell: bash
      run: |
        STAGE=${{ inputs.stage }}
        SERVERLESS_STAGE=`echo $STAGE | awk '$0 == "PRODUCTION" { print "prd" } $0 != "PRODUCTION" { print "dev" }'`

        echo $STAGE $SERVERLESS_STAGE $AWS_ACCESS_KEY_ID $AWS_SECRET_ACCESS_KEY
        
        # make serverless-deploy STAGE=$SERVERLESS_STAGE
