name: APIs

on:
  workflow_call:
    inputs:
      stage:
        required: true
        type: string

jobs:
  deploy-auth:
    name: Deploy Auth API
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Upload Artifact
        uses: actions/download-artifact@v3
        with:
          name: build-services-apis

      - name: List Dir
        run: |
          tree .

      - name: Deploy
        uses: ./.github/actions/go/deploy
        with:
          path: apis/test1 ## TROCAR
          stage: ${{ inputs.stage }}
    
  deploy-engage-api:
    name: Deploy Engage API
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Upload Artifact
        uses: actions/download-artifact@v3
        with:
          name: build-services-apis

      - name: List Dir
        run: |
          tree .

      - name: Deploy
        uses: ./.github/actions/go/deploy
        with:
          path: apis/test2 ## TROCAR
          stage: ${{ inputs.stage }}
  
  deploy-customer-campaign-match:
    name: Deploy Customer Campaign Match API
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Upload Artifact
        uses: actions/download-artifact@v3
        with:
          name: build-services-apis

      - name: List Dir
        run: |
          tree .

      - name: Deploy
        uses: ./.github/actions/go/deploy
        with:
          path: apis/test2 ## TROCAR
          stage: ${{ inputs.stage }}

  deploy-engage-control-api:
    name: Deploy Engage Control API
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Upload Artifact
        uses: actions/download-artifact@v3
        with:
          name: build-services-apis

      - name: List Dir
        run: |
          tree .

      - name: Deploy
        uses: ./.github/actions/go/deploy
        with:
          path: apis/test2 ## TROCAR
          stage: ${{ inputs.stage }}
