name: Deploy

on:
  workflow_call:
    inputs:
      context:
        required: true
        type: string
      stage:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  deploy-infra:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Deploy
        uses: ./.github/actions/go/deploy
        with:
          path: ./infra/   
          stage: ${{ inputs.stage }}

  deploy-multiregion-infra:
    name: Deploy Multi Region Infrastructure
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Deploy
        uses: ./.github/actions/go/deploy
        with:
          path: ./infra-multiregion/   
          stage: ${{ inputs.stage }}

  deploy-apis:
    needs: 
      - deploy-infra
      - deploy-multiregion-infra
    name: Deploy APIs
    uses: ./.github/workflows/apis.yml
    with:
      stage: ${{ github.event.inputs.stage }}
    secrets: inherit

  deploy-ui:
    needs: 
      - deploy-infra
      - deploy-multiregion-infra
    name: Deploy UI
    uses: ./.github/workflows/ui.yml
    with:
      context: ${{ matrix.context }}
      stage: ${{ github.event.inputs.stage }}
    secrets: inherit
