name: Deploy

on:
  workflow_call:
    inputs:
      context:
        required: true
        type: string
      stage:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  checkout:
    name: Checkout
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

  deploy-infra:
    needs: 
      - checkout
    
    name: Deploy Infrastructure
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: ./.github/actions/go/deploy
        with:
          path: ./infra/   
          stage: ${{ inputs.stage }}

