name: Deploy

on:
  workflow_call:
    inputs:
      context:
        required: true
        type: string
      stage:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  deploy-infra:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Deploy
        uses: ./.github/actions/go/deploy
        with:
          path: ./infra/   
          stage: ${{ inputs.stage }}

  deploy-multiregion-infra:
    name: Deploy Multi Region Infrastructure
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Deploy
        uses: ./.github/actions/go/deploy
        with:
          path: ./infra-multiregion/   
          stage: ${{ inputs.stage }}

  deploy-auth:
    needs: 
      - deploy-infra
      - deploy-multiregion-infra
    name: Deploy Auth API
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Upload Artifact
        uses: actions/download-artifact@v3
        with:
          name: build-services-apis

      - name: List Dir
        run: |
          tree .

      - name: Deploy
        uses: ./.github/actions/go/deploy
        with:
          path: apis/test1 ## TROCAR
          stage: ${{ inputs.stage }}
    
  deploy-engage-api:
    needs: 
      - deploy-infra
      - deploy-multiregion-infra
    name: Deploy Engage API
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Upload Artifact
        uses: actions/download-artifact@v3
        with:
          name: build-services-apis

      - name: List Dir
        run: |
          tree .

      - name: Deploy
        uses: ./.github/actions/go/deploy
        with:
          path: apis/test2 ## TROCAR
          stage: ${{ inputs.stage }}
  
  deploy-customer-campaign-match:
    needs: 
      - deploy-infra
      - deploy-multiregion-infra
    name: Deploy Customer Campaign Match API
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Upload Artifact
        uses: actions/download-artifact@v3
        with:
          name: build-services-apis

      - name: List Dir
        run: |
          tree .

      - name: Deploy
        uses: ./.github/actions/go/deploy
        with:
          path: apis/test2 ## TROCAR
          stage: ${{ inputs.stage }}

  # deploy-engage-control-api:
  #   needs: 
  #     - deploy-infra
  #     - deploy-multiregion-infra
  #   name: Deploy Engage Control API
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #       with:
  #         ref: ${{ github.ref }}

  #     - name: Upload Artifact
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: build-services-apis

  #     - name: List Dir
  #       run: |
  #         tree .

  #     - name: Deploy
  #       uses: ./.github/actions/go/deploy
  #       with:
  #         path: apis/test2 ## TROCAR
  #         stage: ${{ inputs.stage }}

  # deploy-engage-delivery:
  #   needs: 
  #     - deploy-infra
  #     - deploy-multiregion-infra
  #   name: Deploy Engage Delivery Job
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #       with:
  #         ref: ${{ github.ref }}

  #     - name: Upload Artifact
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: build-services-apis

  #     - name: List Dir
  #       run: |
  #         tree .

  #     - name: Deploy
  #       uses: ./.github/actions/go/deploy
  #       with:
  #         path: apis/test2 ## TROCAR
  #         stage: ${{ inputs.stage }}

  # deploy-delivery-sms:
  #   needs: 
  #     - deploy-infra
  #     - deploy-multiregion-infra
  #   name: Deploy Engage Delivery SMS Job
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #       with:
  #         ref: ${{ github.ref }}

  #     - name: Upload Artifact
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: build-services-apis

  #     - name: List Dir
  #       run: |
  #         tree .

  #     - name: Deploy
  #       uses: ./.github/actions/go/deploy
  #       with:
  #         path: apis/test2 ## TROCAR
  #         stage: ${{ inputs.stage }}

  # deploy-delivery-whatsapp:
  #   needs: 
  #     - deploy-infra
  #     - deploy-multiregion-infra
  #   name: Deploy Engage Delivery WhatsApp Job
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #       with:
  #         ref: ${{ github.ref }}

  #     - name: Upload Artifact
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: build-services-apis

  #     - name: List Dir
  #       run: |
  #         tree .

  #     - name: Deploy
  #       uses: ./.github/actions/go/deploy
  #       with:
  #         path: apis/test2 ## TROCAR
  #         stage: ${{ inputs.stage }}

  # deploy-datalake:
  #   needs: 
  #     - deploy-infra
  #     - deploy-multiregion-infra
  #   name: Deploy Deltalake Job
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #       with:
  #         ref: ${{ github.ref }}

  #     - name: Upload Artifact
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: build-services-apis

  #     - name: List Dir
  #       run: |
  #         tree .

  #     - name: Deploy
  #       uses: ./.github/actions/go/deploy
  #       with:
  #         path: apis/test2 ## TROCAR
  #         stage: ${{ inputs.stage }}

  # deploy-action-scheduler:
  #   needs: 
  #     - deploy-infra
  #     - deploy-multiregion-infra
  #   name: Deploy Action Scheduler Job
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #       with:
  #         ref: ${{ github.ref }}

  #     - name: Upload Artifact
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: build-services-apis

  #     - name: List Dir
  #       run: |
  #         tree .

  #     - name: Deploy
  #       uses: ./.github/actions/go/deploy
  #       with:
  #         path: apis/test2 ## TROCAR
  #         stage: ${{ inputs.stage }}

  # deploy-action-trigger:
  #   needs: 
  #     - deploy-infra
  #     - deploy-multiregion-infra
  #   name: Deploy Action Trigger Job
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #       with:
  #         ref: ${{ github.ref }}

  #     - name: Upload Artifact
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: build-services-apis

  #     - name: List Dir
  #       run: |
  #         tree .

  #     - name: Deploy
  #       uses: ./.github/actions/go/deploy
  #       with:
  #         path: apis/test2 ## TROCAR
  #         stage: ${{ inputs.stage }}

  # deploy-action-identifier:
  #   needs: 
  #     - deploy-infra
  #     - deploy-multiregion-infra
  #   name: Deploy Action Identifier Job
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #       with:
  #         ref: ${{ github.ref }}

  #     - name: Upload Artifact
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: build-services-apis

  #     - name: List Dir
  #       run: |
  #         tree .

  #     - name: Deploy
  #       uses: ./.github/actions/go/deploy
  #       with:
  #         path: apis/test2 ## TROCAR
  #         stage: ${{ inputs.stage }}

  # deploy-file-process:
  #   needs: 
  #     - deploy-infra
  #     - deploy-multiregion-infra
  #   name: Deploy File Process Job
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #       with:
  #         ref: ${{ github.ref }}

  #     - name: Upload Artifact
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: build-services-apis

  #     - name: List Dir
  #       run: |
  #         tree .

  #     - name: Deploy
  #       uses: ./.github/actions/go/deploy
  #       with:
  #         path: apis/test2 ## TROCAR
  #         stage: ${{ inputs.stage }}

  # deploy-track-notifications:
  #   needs: 
  #     - deploy-infra
  #     - deploy-multiregion-infra
  #   name: Deploy Track Notifications Job
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #       with:
  #         ref: ${{ github.ref }}

  #     - name: Upload Artifact
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: build-services-apis

  #     - name: List Dir
  #       run: |
  #         tree .

  #     - name: Deploy
  #       uses: ./.github/actions/go/deploy
  #       with:
  #         path: apis/test2 ## TROCAR
  #         stage: ${{ inputs.stage }}

  # deploy-current-action-fanout:
  #   needs: 
  #     - deploy-infra
  #     - deploy-multiregion-infra
  #   name: Deploy Current Action FanOut Job
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #       with:
  #         ref: ${{ github.ref }}

  #     - name: Upload Artifact
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: build-services-apis

  #     - name: List Dir
  #       run: |
  #         tree .

  #     - name: Deploy
  #       uses: ./.github/actions/go/deploy
  #       with:
  #         path: apis/test2 ## TROCAR
  #         stage: ${{ inputs.stage }}

  # deploy-action-counter:
  #   needs: 
  #     - deploy-infra
  #     - deploy-multiregion-infra
  #   name: Deploy Action Counter Job
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #       with:
  #         ref: ${{ github.ref }}

  #     - name: Upload Artifact
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: build-services-apis

  #     - name: List Dir
  #       run: |
  #         tree .

  #     - name: Deploy
  #       uses: ./.github/actions/go/deploy
  #       with:
  #         path: apis/test2 ## TROCAR
  #         stage: ${{ inputs.stage }}

  # deploy-deadletters-multiregion:
  #   needs: 
  #     - deploy-infra
  #     - deploy-multiregion-infra
  #   name: Deploy DeadLetters MultiRegion Job
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #       with:
  #         ref: ${{ github.ref }}

  #     - name: Upload Artifact
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: build-services-apis

  #     - name: List Dir
  #       run: |
  #         tree .

  #     - name: Deploy
  #       uses: ./.github/actions/go/deploy
  #       with:
  #         path: apis/test2 ## TROCAR
  #         stage: ${{ inputs.stage }}

  #  deploy-delete-delayed-action:
  #   needs: 
  #     - deploy-infra
  #     - deploy-multiregion-infra
  #   name: Deploy Delete Delayed Action Job
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #       with:
  #         ref: ${{ github.ref }}

  #     - name: Upload Artifact
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: build-services-apis

  #     - name: List Dir
  #       run: |
  #         tree .

  #     - name: Deploy
  #       uses: ./.github/actions/go/deploy
  #       with:
  #         path: apis/test2 ## TROCAR
  #         stage: ${{ inputs.stage }}

  # deploy-delete-campaign-action:
  #   needs: 
  #     - deploy-infra
  #     - deploy-multiregion-infra
  #   name: Deploy Delete Campaign Action Job
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #       with:
  #         ref: ${{ github.ref }}

  #     - name: Upload Artifact
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: build-services-apis

  #     - name: List Dir
  #       run: |
  #         tree .

  #     - name: Deploy
  #       uses: ./.github/actions/go/deploy
  #       with:
  #         path: apis/test2 ## TROCAR
  #         stage: ${{ inputs.stage }}

  # deploy-workflow-events-consumer:
  #   needs: 
  #     - deploy-infra
  #     - deploy-multiregion-infra
  #   name: Deploy Workflow Events Consumer Job
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #       with:
  #         ref: ${{ github.ref }}

  #     - name: Upload Artifact
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: build-services-apis

  #     - name: List Dir
  #       run: |
  #         tree .

  #     - name: Deploy
  #       uses: ./.github/actions/go/deploy
  #       with:
  #         path: apis/test2 ## TROCAR
  #         stage: ${{ inputs.stage }}


  # deploy-ui:
  #   needs: 
  #     - deploy-infra
  #     - deploy-multiregion-infra
  #   name: Deploy UI
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #       with:
  #         ref: ${{ github.ref }}

  #     - name: Upload Artifact
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: build-services-apis

  #     - name: List Dir
  #       run: |
  #         tree .

  #     - name: Deploy
  #       uses: ./.github/actions/go/deploy
  #       with:
  #         path: apis/test2 ## TROCAR
  #         stage: ${{ inputs.stage }}

  # deploy-ui-unsubscribe:
    # needs: 
    #   - deploy-infra
    #   - deploy-multiregion-infra
    # name: Deploy UI Unsubscribe
    # runs-on: ubuntu-latest
    # steps:
    #   - name: Checkout
    #     uses: actions/checkout@v3
    #     with:
    #       ref: ${{ github.ref }}

    #   - name: Upload Artifact
    #     uses: actions/download-artifact@v3
    #     with:
    #       name: build-services-apis

    #   - name: List Dir
    #     run: |
    #       tree .

    #   - name: Deploy
    #     uses: ./.github/actions/go/deploy
    #     with:
    #       path: apis/test2 ## TROCAR
    #       stage: ${{ inputs.stage }}
