name: Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: choice
        default: dev
        options:
          - dev
          - prod
      context:
        required: true
        description: List of context to be deployed. Eg. "['ampli', 'fibra', 'mobi']"
        type: string
      version:
        required: true
        description: Tag Semantic Version for deploy
        type: string

jobs:
  Test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        context: ${{ fromJSON(github.event.inputs.context)}}

    steps:
      - name: Echo Matrix Value
        run: |
          echo ${{ matrix.context }}

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
