name: Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: choice
        default: DEVELOPMENT
        options:
          - DEVELOPMENT
          - PRODUCTION
      context:
        required: true
        description: List of context to be deployed. Eg. "['ampli', 'fibra', 'mobi']"
        type: string

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        context: ${{ fromJSON(github.event.inputs.context)}}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Setup Golang
        uses: actions/setup-go@v4
        with:
          go-version: 1.18.1

      - name: Test
        run: |
          cd ./services/${{ github.workflow }}
          make test

  deploy-infra:
    name: Deploy Infra
    runs-on: ubuntu-latest
    env:
      STAGE: ${{ github.event.inputs.environment }}
      SERVERLESS_STAGE: ${{ github.event.inputs.environment == 'PRODUCTION' && 'prd' || 'dev' }}
      AWS_ACCESS_KEY_ID: ${{ format('secrets.AWS_ACCESS_KEY_ID_{0}_{1}', github.event.inputs.environment, matrix.context) }}
      AWS_SECRET_ACCESS_KEY: ${{ format('secrets.AWS_SECRET_ACCESS_KEY_{0}_{1}', github.event.inputs.environment, matrix.context) }}
    strategy:
      matrix:
        context: ${{ fromJSON(github.event.inputs.context)}}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v3

      - name: Deploy Dev
        run: |
          npm install -g serverless@3.x
          echo Test
          # cd ./services/${{ github.workflow }}
          # make serverless-deploy STAGE=$SERVERLESS_STAGE
