name: Deploy

on:
  workflow_call:
    inputs:
      context:
        required: true
        type: string
      stage:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  deploy-infra:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Deploy
        uses: ./.github/actions/go/deploy
        with:
          path: ./infra/   
          stage: ${{ inputs.stage }}

  deploy-multiregion-infra:
    name: Deploy Multi Region Infrastructure
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Deploy
        uses: ./.github/actions/go/deploy
        with:
          path: ./infra-multiregion/   
          stage: ${{ inputs.stage }}

  deploy-auth:
    needs: 
      - deploy-infra
      - deploy-multiregion-infra
    name: Deploy Auth API
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Upload Artifact
        uses: actions/download-artifact@v3
        with:
          name: build-services-apis-test1
          path: apis/test1/bin/

      - name: list dir
        run: |
          tree .
      - name: Deploy
        uses: ./.github/actions/go/deploy
        with:
          path: apis/test1
          stage: ${{ inputs.stage }}
