name: Deploy

on:
  workflow_dispatch:
    inputs:
      stage:
        required: true
        type: choice
        default: DEVELOPMENT
        options:
          - DEVELOPMENT
          - PRODUCTION
      context:
        required: true
        description: List of context to be deployed. Eg. "['ampli', 'fibra', 'mobi']"
        type: string

jobs:

  deploy-infra:
    name: Deploy Infra
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ format('AWS_ACCESS_KEY_ID_{0}_{1}', github.event.inputs.stage, matrix.context) }}
      AWS_SECRET_ACCESS_KEY: ${{ format('AWS_SECRET_ACCESS_KEY_{0}_{1}', github.event.inputs.stage, matrix.context) }}
    strategy:
      matrix:
        context: ${{ fromJSON(github.event.inputs.context)}}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Deploy
        uses: ./.github/actions/deploy
        with:
          path: Test
          stage: github.event.inputs.stage

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: test
          path: test.txt

  Test:
    needs:
      - deploy-infra
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: test
