name: Infra

on:
  workflow_call:
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  deploy-infra:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Checkout Repo
        run: |
          tree /home/runner/work

      - name: Deploy
        uses: ./.github/actions/deploy
        with:
          path: Test
          stage: github.event.inputs.stage

