name: Infra

on:
  workflow_call:
    inputs:
      context:
        required: true
        type: string
      stage:
        required: true
        type: string

jobs:
  deploy-infra:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Deploy
        uses: ./.github/actions/go/deploy
        with:
          path: ./infra/   
          stage: ${{ inputs.stage }}

