name: Trigger Pipeline

on:
  workflow_dispatch:
    inputs:
      stage:
        required: true
        type: choice
        default: DEVELOPMENT
        options:
          - DEVELOPMENT
          - PRODUCTION
      context:
        required: true
        description: List of context to be deployed. Eg. "['ampli', 'fibra', 'mobi']"
        type: string

jobs:
  list-services:
    name: List Services
    runs-on: ubuntu-latest
    env:
      SERVICES_FOLDERS: apis jobs
    outputs:
      services: ${{ steps.set-services.outputs.services }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Set Services List
        id: set-services
        shell: bash
        run: |
          read -r -a SERVICES_FOLDERS <<< "$SERVICES_FOLDERS"
          VALUES=$(printf ', "%s"' "${SERVICES_FOLDERS[@]}")
          SERVICES_FOLDERS="["${VALUES:2}"]"
          echo $SERVICES_FOLDERS

          echo "services=$(echo $SERVICES_FOLDERS)" >> $GITHUB_OUTPUT

  test-services:
    needs: list-services
    name: Test Services
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        service: ${{ fromJSON(needs.list-services.outputs.services) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Test Services
        working-directory: ${{ matrix.service }}
        run: |
          for SERVICE in ./*; do
            if [ -d "$SERVICE" ]; then
              echo $SERVICE
              cd $SERVICE
              make test
              cd -
            fi;
          done;

  build-services:
    needs: 
      - list-services
    name: Build Services
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        service: ${{ fromJSON(needs.list-services.outputs.services) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.18.1

      - name: Build Services
        working-directory: ${{ matrix.service }}
        run: |
          for SERVICE in ./*; do
            if [ -d "$SERVICE" ]; then
              cd $SERVICE
              make build
              cd -
            fi;
          done;
      
      - name: List Folder
        run: |
          tree ${{ matrix.service }}

      - name: Publish Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-services-${{ matrix.service }}
          path: ${{ matrix.service }}/**/bin/*.zip
  
  list-uis:
    name: List UIs
    runs-on: ubuntu-latest
    env:
      UI_FOLDERS: ui ui-unsubscribe
    outputs:
      uis: ${{ steps.set-ui.outputs.uis }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Set UI List
        id: set-ui
        shell: bash
        run: |
          read -r -a UI_FOLDERS <<< "$UI_FOLDERS"
          VALUES=$(printf ', "%s"' "${UI_FOLDERS[@]}")
          UI_FOLDERS="["${VALUES:2}"]"
          echo $UI_FOLDERS

          echo "uis=$(echo $UI_FOLDERS)" >> $GITHUB_OUTPUT

  build-ui:
    needs: 
      - list-uis
    name: Build UI
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        ui: ${{ fromJSON(needs.list-uis.outputs.uis) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
      
      - name: Install Dependencies
        working-directory: ${{ matrix.ui }}
        run: |
          yarn install --frozen-lockfile

      - name: Build UI
        working-directory: ${{ matrix.ui }}
        run: |
          BUILD_MODE=`echo $STAGE | awk '$0 == "DEVELOPMENT" { print "STAGING" } $0 != "DEVELOPMENT" { print $0 }'`
          yarn build --mode $BUILD_MODE
      
      - name: List Folder
        run: |
          tree ${{ matrix.ui }}

      - name: Publish Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-uis-${{ matrix.ui }}
          path: ${{ matrix.ui }}/dist/**

  deploy:
    needs: 
      - build-services
    name: Deploy
    uses: ./.github/workflows/deploy.yml
    strategy:
      matrix:
        context: ${{ fromJSON(github.event.inputs.context) }}
    with:
      context: ${{ matrix.context }}
      stage: ${{ github.event.inputs.stage }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets[format('AWS_ACCESS_KEY_ID_{0}_{1}', github.event.inputs.stage, matrix.context)] }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets[format('AWS_SECRET_ACCESS_KEY_{0}_{1}', github.event.inputs.stage, matrix.context)] }}
