name: Trigger Pipeline

on:
  workflow_dispatch:
    inputs:
      stage:
        required: true
        type: choice
        default: DEVELOPMENT
        options:
          - DEVELOPMENT
          - PRODUCTION
      context:
        required: true
        description: List of context to be deployed. Eg. "['ampli', 'fibra', 'mobi']"
        type: string

jobs:

  deploy-infra:
    name: Deploy Infra
    uses: DevLucca/go-github-action/.github/workflow/infra.yml@main
    strategy:
      matrix:
        context: ${{ fromJSON(github.event.inputs.context)}}
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets[format('AWS_ACCESS_KEY_ID_{0}_{1}', github.event.inputs.stage, matrix.context)] }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets[format('AWS_SECRET_ACCESS_KEY_{0}_{1}', github.event.inputs.stage, matrix.context)] }}

  Test:
    needs:
      - deploy-infra
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: test
