name: UI

on:
  workflow_call:
    inputs:
      context:
        required: true
        type: string
      stage:
        required: true
        type: string

jobs:
  deploy-ui:
    name: Deploy UI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: build-uis-ui

      - name: List Dir
        run: |
          tree .

      - name: Deploy
        uses: ./.github/actions/ui/deploy
        with:
          path: ui
          stage: ${{ inputs.stage }}

  deploy-ui-unsubscribe:
    name: Deploy UI Unsubscribe
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: build-uis-ui-unsubscribe

      - name: List Dir
        run: |
          tree .

      - name: Deploy
        uses: ./.github/actions/ui/deploy
        with:
          path: ui-unsubscribe
          stage: ${{ inputs.stage }}
